name: natural_computing
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pip
  - numba
  - pandas
  - scikit-learn
  - pip:
    - click
    - joblib
    - tqdm
    - matplotlib
    - orjson
